# Generated by Django 3.0.7 on 2023-06-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rollnumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
