# Generated by Django 3.0.7 on 2023-06-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0002_students_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
