# Generated by Django 3.0.7 on 2023-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0004_auto_20230618_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssdd', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], default='Select', max_length=100)),
                ('cdd', models.CharField(choices=[('V', 'v'), ('I', 'i'), ('B', 'b'), ('G', 'g'), ('O', 'o')], default='Select', max_length=100)),
            ],
        ),
    ]
