# Generated by Django 3.0.7 on 2023-06-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0006_auto_20230619_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregister',
            old_name='cdd',
            new_name='Coursee',
        ),
        migrations.RenameField(
            model_name='courseregister',
            old_name='ssdd',
            new_name='Stafff',
        ),
    ]
