# Generated by Django 3.0.7 on 2023-06-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0007_auto_20230620_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregister',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_001.Students'),
            preserve_default=False,
        ),
    ]
