# Generated by Django 3.0.7 on 2023-06-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0008_courseregister_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregister',
            old_name='student_id',
            new_name='studentid',
        ),
    ]
