# Generated by Django 3.0.7 on 2023-06-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0009_auto_20230622_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='admin',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
