# Generated by Django 3.0.7 on 2023-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0010_auto_20230626_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregister',
            name='timess',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
