# Generated by Django 3.0.7 on 2023-07-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0011_courseregister_timess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregister',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
