# Generated by Django 3.0.7 on 2023-07-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0012_auto_20230701_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
