# Generated by Django 3.0.7 on 2023-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0017_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Student'), (3, 'Staff')], default=1, max_length=10),
        ),
    ]
