# Generated by Django 3.0.7 on 2023-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0020_addcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
